version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/next/Dockerfile
    tty: true
    ports:
      - 8080:3000
    volumes:
      - ./src:/app
        #command: sh -c "npm run dev"
    environment:
      - WATCHPACK_POLLING=true

  nest:
    build:
      context: .
      dockerfile: ./docker/nest/Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./deliverer:/app
